# Changes here will be overwritten by Copier
_commit: v2.2.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
create_example_module: true
custom_install: custom
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: ppdb_hats
project_description: Pipeline tools to ingest Rubin PPDB into HATS.
project_license: BSD
project_name: ppdb_hats
project_organization: astronomy-commons
python_versions:
- '3.11'
- '3.12'
- '3.13'
test_lowest_version: none
